# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
    - NODE_VERSION: "4"
      NPM_VERSION: "3"
    - NODE_VERSION: "5"
      NPM_VERSION: "3"
    - NODE_VERSION: "6"
      NPM_VERSION: "3"
    - NODE_VERSION: "7"
      NPM_VERSION: "3"
      NPM_VERSION: "4"
    - NODE_VERSION: "8"
      NPM_VERSION: "4"
      NPM_VERSION: "5"

platform:
  - x86
  - x64

init:
 - git config --global core.autocrlf true

cache:
  - AllReadyApp\Web-App\AllReady\node_modules   # node modules for the app
  - '%APPDATA%\npm-cache'                       # npm cache

install:
  - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
  - choco install firefox -version 43.0.3
  - ps: Install-Product node $env:NODE_VERSION
  - node --version
  - npm --version
  - npm install -g npm@%NPM_VERSION%
  - npm install -g gulp
  - npm install -g jshint
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g istanbul-coveralls
  - npm install -g nodeunit
  - npm install

build: off

test_script:
  - npm test
